# Generated by Django 4.2.21 on 2025-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('SUNDAY_SERVICE', 'Sunday Service'), ('BIBLE_STUDY', 'Bible Study'), ('PRAYER_MEETING', 'Prayer Meeting'), ('SPECIAL_EVENT', 'Special Event')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
