# Generated by Django 4.2.21 on 2025-11-08 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("worship", "Worship"),
                            ("outreach", "Outreach"),
                            ("care", "Care"),
                            ("logistics", "Logistics"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "activity_cadence",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("seasonal", "Seasonal"),
                            ("event_driven", "Event Driven"),
                            ("holiday", "Holiday"),
                            ("ad_hoc", "Ad Hoc"),
                        ],
                        default="weekly",
                        max_length=30,
                    ),
                ),
                ("meeting_location", models.CharField(blank=True, max_length=255)),
                ("meeting_schedule", models.JSONField(blank=True, null=True)),
                ("communication_channel", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ministries_primary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_coordinators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ministries_supporting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "verbose_name_plural": "Ministries",
            },
        ),
        migrations.CreateModel(
            name="MinistryMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary_coordinator", "Primary Coordinator"),
                            ("coordinator", "Coordinator"),
                            ("team_member", "Team Member"),
                            ("guest_helper", "Guest Helper"),
                        ],
                        default="team_member",
                        max_length=30,
                    ),
                ),
                (
                    "join_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("availability", models.JSONField(blank=True, default=dict)),
                ("skills", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ministry_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ministry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="ministries.ministry",
                    ),
                ),
            ],
            options={
                "ordering": ("ministry", "member"),
                "unique_together": {("ministry", "member")},
            },
        ),
    ]
