# Generated by Django 4.2.23 on 2025-12-10 17:48

import apps.ministries.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_branch_alter_journey_type_delete_cluster_and_more"),
        ("ministries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ministry",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ministries",
                to="people.branch",
            ),
        ),
        migrations.AlterField(
            model_name="ministrymember",
            name="join_date",
            field=models.DateField(default=apps.ministries.models.today),
        ),
    ]
