# Generated by Django 4.2.23 on 2026-08-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministries", "0004_ncc_system_ministry"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ministry",
            name="ministries_code_branch_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="ministry",
            name="ministries_code_national_uniq",
        ),
        migrations.AddConstraint(
            model_name="ministry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", False), ("code__isnull", False)),
                fields=("code", "branch"),
                name="ministries_code_branch_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="ministry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("branch__isnull", True), ("code__isnull", False)),
                fields=("code",),
                name="ministries_code_national_uniq",
            ),
        ),
    ]
