# Generated by Django 4.2.23 on 2025-11-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0003_alter_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SundaySchoolCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("min_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sunday School Category",
                "verbose_name_plural": "Sunday School Categories",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="SundaySchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("yearly_theme", models.CharField(blank=True, max_length=200)),
                ("room_location", models.CharField(blank=True, max_length=200)),
                ("meeting_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classes",
                        to="sunday_school.sundayschoolcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sunday School Class",
                "verbose_name_plural": "Sunday School Classes",
                "ordering": ("category__order", "name"),
            },
        ),
        migrations.CreateModel(
            name="SundaySchoolSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                ("session_time", models.TimeField(blank=True, null=True)),
                ("lesson_title", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("is_recurring_instance", models.BooleanField(default=False)),
                ("recurring_group_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sunday_school_session",
                        to="events.event",
                    ),
                ),
                (
                    "sunday_school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="sunday_school.sundayschoolclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sunday School Session",
                "verbose_name_plural": "Sunday School Sessions",
                "ordering": ("-session_date", "-session_time"),
            },
        ),
        migrations.CreateModel(
            name="SundaySchoolClassMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TEACHER", "Teacher"),
                            ("ASSISTANT_TEACHER", "Assistant Teacher"),
                            ("STUDENT", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enrolled_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunday_school_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sunday_school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="sunday_school.sundayschoolclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sunday School Class Member",
                "verbose_name_plural": "Sunday School Class Members",
                "ordering": (
                    "sunday_school_class",
                    "role",
                    "person__last_name",
                    "person__first_name",
                ),
                "unique_together": {("sunday_school_class", "person")},
            },
        ),
    ]
