# Generated by Django 4.2.21 on 2025-05-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_leader', to='members.user')),
            ],
        ),
        migrations.CreateModel(
            name='MinistryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('availability', models.JSONField(default=dict)),
                ('skills', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.ministry')),
            ],
            options={
                'unique_together': {('ministry', 'member')},
            },
        ),
    ]
