# Generated by Django 4.2.23 on 2025-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("SUNDAY_SERVICE", "Sunday Service"),
                    ("BIBLE_STUDY", "Bible Study"),
                    ("PRAYER_MEETING", "Prayer Meeting"),
                    ("CLUSTER_BS_EVANGELISM", "Cluster/BS Evangelism"),
                    ("CLUSTERING", "Clustering"),
                    ("DOCTRINAL_CLASS", "Doctrinal Class"),
                    ("CYM_CLASS", "CYM Class"),
                    ("MINI_WORSHIP", "Mini Worship"),
                    ("GOLDEN_WARRIORS", "Golden Warriors"),
                    ("CAMPING", "Camping"),
                    ("AWTA", "AWTA"),
                    ("CONFERENCE", "Conference"),
                    ("SUNDAY_SCHOOL", "Sunday School"),
                    ("OTHER", "Others"),
                ],
                default="SUNDAY_SERVICE",
                max_length=50,
            ),
        ),
    ]
