# Generated by Django 4.2.23 on 2026-09-11 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_people_automation_setting'),
        ('events', '0003_eventtype_color_is_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rooms', to='people.branch')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventroom'),
        ),
        migrations.AddIndex(
            model_name='eventroom',
            index=models.Index(fields=['branch', 'is_active'], name='events_even_branch__2c5684_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventroom',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('branch'), name='events_eventroom_branch_lname_uniq'),
        ),
    ]
