# Generated by Django 4.2.23 on 2025-12-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_branch_alter_journey_type_delete_cluster_and_more"),
        ("events", "0003_alter_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="people.branch",
            ),
        ),
    ]
