# Generated by Django 4.2.23 on 2026-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventroom_and_event_room_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="expected_include_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="expected_include_semiactive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="expected_include_inactive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="expected_include_ongoing_visitors",
            field=models.BooleanField(default=True),
        ),
    ]
