# Generated by Django 4.2.23 on 2026-09-12 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_event_setting(apps, schema_editor):
    EventSetting = apps.get_model("events", "EventSetting")
    EventSetting.objects.get_or_create(
        pk=1,
        defaults={"member_self_checkin_enabled": False},
    )


def unseed_event_setting(apps, schema_editor):
    EventSetting = apps.get_model("events", "EventSetting")
    EventSetting.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_event_expected_attendee_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_self_checkin_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, all logged-in members can use Sunday self-check-in. When disabled, only admins and Events coordinators see it.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_event_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Setting",
                "verbose_name_plural": "Event Settings",
            },
        ),
        migrations.RunPython(seed_event_setting, unseed_event_setting),
    ]
