# Generated by Django 4.2.23 on 2025-11-22 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="authenticat_user_id_33a635_idx",
            old_name="authenticat_user_id_action_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="authenticat_action_4a725a_idx",
            old_name="authenticat_action_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="authenticat_timesta_ba49b1_idx",
            old_name="authenticat_timestamp_idx",
        ),
        migrations.AddField(
            model_name="passwordresetrequest",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="passwordresetrequest",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_password_resets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILURE", "Login Failure"),
                    ("LOGOUT", "Logout"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_RESET_REQUEST", "Password Reset Request"),
                    ("PASSWORD_RESET_APPROVED", "Password Reset Approved"),
                    ("PASSWORD_RESET_REJECTED", "Password Reset Rejected"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("TOKEN_REFRESH", "Token Refresh"),
                    ("ROLE_CHANGE", "Role Change"),
                    ("ACCOUNT_ACTIVATED", "Account Activated"),
                    ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                ],
                max_length=50,
            ),
        ),
    ]
