# Generated by Django 4.2.23 on 2026-06-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_rename_authenticat_user_id_action_idx_authenticat_user_id_33a635_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILURE", "Login Failure"),
                    ("LOGOUT", "Logout"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_RESET_REQUEST", "Password Reset Request"),
                    ("PASSWORD_RESET_APPROVED", "Password Reset Approved"),
                    ("PASSWORD_RESET_REJECTED", "Password Reset Rejected"),
                    ("ADMIN_PASSWORD_RESET", "Admin Password Reset"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("TOKEN_REFRESH", "Token Refresh"),
                    ("ROLE_CHANGE", "Role Change"),
                    ("ACCOUNT_ACTIVATED", "Account Activated"),
                    ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                ],
                max_length=50,
            ),
        ),
    ]
