# Generated by Django 4.2.23 on 2025-12-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clusters", "0002_cluster_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterComplianceNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="Note about compliance issue or follow-up action"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        help_text="Start date of compliance period this note refers to"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="End date of compliance period this note refers to"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_notes",
                        to="clusters.cluster",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_compliance_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cluster", "-created_at"],
                        name="clusters_cl_cluster_dc7591_idx",
                    )
                ],
            },
        ),
    ]
