# Generated by Django 4.2.23 on 2026-04-30 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clusters", "0003_add_cluster_compliance_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterweeklyreport",
            name="members_attended",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role__in": ["MEMBER", "COORDINATOR"]},
                related_name="cluster_reports_as_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
