# Generated by Django 4.2.23 on 2026-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_alter_clusterweeklyreport_members_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
