# Generated by Django 4.2.23 on 2026-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0001_initial'),
        ('clusters', '0005_soft_delete_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterweeklyreport',
            name='prospects_invited',
            field=models.ManyToManyField(blank=True, help_text='Invited visitors recorded on this report (not yet attended)', related_name='cluster_reports_invited_to', to='evangelism.prospect'),
        ),
    ]
