# Generated by Django 4.2.23 on 2026-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0006_clusterweeklyreport_prospects_invited'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['is_active'], name='cl_cluster_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['branch', 'name'], name='cl_cluster_br_name_idx'),
        ),
    ]
