# Generated by Django 4.2.23 on 2026-08-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0007_cluster_list_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clusterweeklyreport',
            index=models.Index(fields=['year', 'week_number'], name='clusters_cl_year_10a4d0_idx'),
        ),
    ]
