# Generated by Django 4.2.23 on 2025-11-19 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clusters", "0001_initial"),
        ("events", "0003_alter_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvangelismGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("meeting_time", models.TimeField(blank=True, null=True)),
                (
                    "meeting_day",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evangelism_groups",
                        to="clusters.cluster",
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinated_evangelism_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evangelism Group",
                "verbose_name_plural": "Evangelism Groups",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact_info", models.CharField(blank=True, max_length=200)),
                (
                    "pipeline_stage",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ATTENDED", "Attended"),
                            ("BAPTIZED", "Baptized"),
                            ("RECEIVED_HG", "Received Holy Ghost"),
                            ("CONVERTED", "Converted"),
                        ],
                        default="INVITED",
                        max_length=20,
                    ),
                ),
                ("first_contact_date", models.DateField(blank=True, null=True)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("is_attending_cluster", models.BooleanField(default=False)),
                ("is_dropped_off", models.BooleanField(default=False)),
                ("drop_off_date", models.DateField(blank=True, null=True)),
                (
                    "drop_off_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INVITED", "Invited"),
                            ("ATTENDED", "Attended"),
                            ("BAPTIZED", "Baptized"),
                            ("RECEIVED_HG", "Received Holy Ghost"),
                            ("CONVERTED", "Converted"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("drop_off_reason", models.TextField(blank=True)),
                ("has_finished_lessons", models.BooleanField(default=False)),
                ("commitment_form_signed", models.BooleanField(default=False)),
                (
                    "fast_track_reason",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("GOING_ABROAD", "Going Abroad"),
                            ("HEALTH_ISSUES", "Health Issues"),
                            ("OTHER", "Other"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endorsed_cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsed_prospects",
                        to="clusters.cluster",
                    ),
                ),
                (
                    "evangelism_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects",
                        to="evangelism.evangelismgroup",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited_prospects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter_cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects_by_inviter",
                        to="clusters.cluster",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospect_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospect",
                "verbose_name_plural": "Prospects",
                "ordering": ("-last_activity_date", "name"),
            },
        ),
        migrations.CreateModel(
            name="FollowUpTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("PHONE_CALL", "Phone Call"),
                            ("TEXT_MESSAGE", "Text Message"),
                            ("VISIT", "Visit"),
                            ("EMAIL", "Email"),
                            ("PRAYER", "Prayer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_follow_up_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_follow_up_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_up_tasks",
                        to="evangelism.prospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow-up Task",
                "verbose_name_plural": "Follow-up Tasks",
                "ordering": ("due_date", "priority"),
            },
        ),
        migrations.CreateModel(
            name="EvangelismSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                ("session_time", models.TimeField(blank=True, null=True)),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("is_recurring_instance", models.BooleanField(default=False)),
                ("recurring_group_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evangelism_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="evangelism.evangelismgroup",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evangelism_session",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evangelism Session",
                "verbose_name_plural": "Evangelism Sessions",
                "ordering": ("-session_date", "-session_time"),
            },
        ),
        migrations.CreateModel(
            name="DropOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drop_off_date", models.DateField()),
                (
                    "drop_off_stage",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ATTENDED", "Attended"),
                            ("BAPTIZED", "Baptized"),
                            ("RECEIVED_HG", "Received Holy Ghost"),
                            ("CONVERTED", "Converted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("days_inactive", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_CONTACT", "No Contact"),
                            ("NO_SHOW", "No Show"),
                            ("LOST_INTEREST", "Lost Interest"),
                            ("MOVED", "Moved"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_details", models.TextField(blank=True)),
                ("recovery_attempted", models.BooleanField(default=False)),
                ("recovery_date", models.DateField(blank=True, null=True)),
                ("recovered", models.BooleanField(default=False)),
                ("recovered_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prospect",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drop_off_record",
                        to="evangelism.prospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drop-off",
                "verbose_name_plural": "Drop-offs",
                "ordering": ("-drop_off_date",),
            },
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversion_date", models.DateField()),
                ("water_baptism_date", models.DateField(blank=True, null=True)),
                ("spirit_baptism_date", models.DateField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="clusters.cluster",
                    ),
                ),
                (
                    "converted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evangelism_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="evangelism.evangelismgroup",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="evangelism.prospect",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_conversions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversion",
                "verbose_name_plural": "Conversions",
                "ordering": ("-conversion_date",),
            },
        ),
        migrations.CreateModel(
            name="MonthlyConversionTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("INVITED", "Invited"),
                            ("ATTENDED", "Attended"),
                            ("BAPTIZED", "Baptized"),
                            ("RECEIVED_HG", "Received Holy Ghost"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                ("first_date_in_stage", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_conversion_tracking",
                        to="clusters.cluster",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_conversion_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_tracking",
                        to="evangelism.prospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Conversion Tracking",
                "verbose_name_plural": "Monthly Conversion Tracking",
                "ordering": ("-year", "-month", "stage"),
                "indexes": [
                    models.Index(
                        fields=["cluster", "year", "month", "stage"],
                        name="evangelism__cluster_53c373_idx",
                    )
                ],
                "unique_together": {("cluster", "prospect", "year", "month", "stage")},
            },
        ),
        migrations.CreateModel(
            name="EvangelismWeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(help_text="Year of the report (e.g., 2025)"),
                ),
                (
                    "week_number",
                    models.IntegerField(help_text="ISO week number (1-53)"),
                ),
                (
                    "meeting_date",
                    models.DateField(
                        help_text="Actual date the meeting was held this week"
                    ),
                ),
                (
                    "gathering_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical"),
                            ("ONLINE", "Online"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("activities_held", models.TextField(blank=True)),
                ("prayer_requests", models.TextField(blank=True)),
                ("testimonies", models.TextField(blank=True)),
                ("new_prospects", models.IntegerField(default=0)),
                ("conversions_this_week", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evangelism_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to="evangelism.evangelismgroup",
                    ),
                ),
                (
                    "members_attended",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "MEMBER"},
                        related_name="evangelism_reports_as_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_evangelism_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visitors_attended",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "VISITOR"},
                        related_name="evangelism_reports_as_visitor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evangelism Weekly Report",
                "verbose_name_plural": "Evangelism Weekly Reports",
                "ordering": ["-year", "-week_number"],
                "unique_together": {("evangelism_group", "year", "week_number")},
            },
        ),
        migrations.CreateModel(
            name="EvangelismGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LEADER", "Leader"),
                            ("MEMBER", "Member"),
                            ("ASSISTANT_LEADER", "Assistant Leader"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joined_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "evangelism_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="evangelism.evangelismgroup",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evangelism_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evangelism Group Member",
                "verbose_name_plural": "Evangelism Group Members",
                "ordering": (
                    "evangelism_group",
                    "role",
                    "person__last_name",
                    "person__first_name",
                ),
                "unique_together": {("evangelism_group", "person")},
            },
        ),
        migrations.CreateModel(
            name="Each1Reach1Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("target_conversions", models.IntegerField()),
                ("achieved_conversions", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("NOT_STARTED", "Not Started"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="each1reach1_goals",
                        to="clusters.cluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Each 1 Reach 1 Goal",
                "verbose_name_plural": "Each 1 Reach 1 Goals",
                "ordering": ("-year", "cluster__name"),
                "unique_together": {("cluster", "year")},
            },
        ),
    ]
