# Generated by Django 4.2.23 on 2025-11-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evangelism", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evangelismgroup",
            name="is_bible_sharers_group",
            field=models.BooleanField(
                default=False,
                help_text="Mark this group as a Bible Sharers group. Bible Sharers are capable of facilitating bible studies and can step in when a cluster doesn't have someone to facilitate.",
            ),
        ),
    ]
