# Generated by Django 4.2.23 on 2026-08-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evangelismweeklyreport',
            index=models.Index(fields=['year', 'week_number'], name='evangelism__year_8b5a3c_idx'),
        ),
    ]
