# Generated by Django 4.2.21 on 2025-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_first_attended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last middle_name'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('BAPTISM', 'Baptism'), ('SPIRIT', 'Spirit'), ('CLUSTER', 'Cluster')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('VISITOR', 'Visitor'), ('COORDINATOR', 'Coordinator'), ('PASTOR', 'Pastor'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
