# Generated by Django 4.2.21 on 2025-07-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AddField(
            model_name='milestone',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='date_first_attended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='facebook_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_inviter', to='members.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='middle_name'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('SEMIACTIVE', 'Semiactive'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='suffix',
            field=models.CharField(blank=True, max_length=150, verbose_name='suffix'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='type',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('BAPTISM', 'Baptism'), ('SPIRIT', 'Spirit'), ('CLUSTER', 'Cluster'), ('NOTE', 'Note')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('VISITOR', 'Visitor'), ('COORDINATOR', 'Coordinator'), ('PASTOR', 'Pastor'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
