# Generated by Django 4.2.23 on 2025-10-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
