# Generated by Django 4.2.23 on 2025-10-20 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_family_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="cluster",
            name="meeting_schedule",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cluster",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="clusters", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="families",
            field=models.ManyToManyField(blank=True, to="people.family"),
        ),
    ]
