# Generated by Django 4.2.23 on 2025-10-22 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_cluster_location_cluster_members_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterWeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(help_text="Year of the report (e.g., 2025)"),
                ),
                (
                    "week_number",
                    models.IntegerField(help_text="ISO week number (1-53)"),
                ),
                (
                    "meeting_date",
                    models.DateField(
                        help_text="Actual date the cluster meeting was held this week"
                    ),
                ),
                ("members_present", models.IntegerField(default=0)),
                ("visitors_present", models.IntegerField(default=0)),
                (
                    "gathering_type",
                    models.CharField(
                        choices=[
                            ("PHYSICAL", "Physical"),
                            ("ONLINE", "Online"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activities_held",
                    models.TextField(
                        blank=True,
                        help_text="Activities/events held during the cluster meeting",
                    ),
                ),
                ("prayer_requests", models.TextField(blank=True)),
                ("testimonies", models.TextField(blank=True)),
                (
                    "offerings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "highlights",
                    models.TextField(
                        blank=True, help_text="Positive events or achievements"
                    ),
                ),
                (
                    "lowlights",
                    models.TextField(blank=True, help_text="Challenges or concerns"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_reports",
                        to="people.cluster",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_cluster_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-week_number"],
                "unique_together": {("cluster", "year", "week_number")},
            },
        ),
    ]
