# Generated by Django 4.2.23 on 2025-11-22 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_add_password_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleCoordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("CLUSTER", "Cluster"),
                            ("FINANCE", "Finance"),
                            ("EVANGELISM", "Evangelism"),
                            ("SUNDAY_SCHOOL", "Sunday School"),
                            ("LESSONS", "Lessons"),
                            ("EVENTS", "Events"),
                            ("MINISTRIES", "Ministries"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("COORDINATOR", "Coordinator"),
                            ("SENIOR_COORDINATOR", "Senior Coordinator"),
                            ("TEACHER", "Teacher"),
                            ("BIBLE_SHARER", "Bible Sharer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.IntegerField(
                        blank=True,
                        help_text="For resource-specific assignments (e.g., specific cluster ID)",
                        null=True,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of resource (e.g., 'Cluster', 'EvangelismGroup')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_coordinator_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Coordinator",
                "verbose_name_plural": "Module Coordinators",
                "ordering": ["person", "module", "level"],
            },
        ),
        migrations.AddIndex(
            model_name="modulecoordinator",
            index=models.Index(
                fields=["person", "module"], name="people_modu_person__8bd407_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modulecoordinator",
            unique_together={("person", "module", "resource_id")},
        ),
    ]
