# Generated by Django 4.2.23 on 2025-11-22 05:12

from django.db import migrations


def migrate_coordinators_to_module_assignments(apps, schema_editor):
    """
    Convert existing COORDINATOR role users to Cluster Coordinators.
    This preserves existing permissions during the transition.
    """
    Person = apps.get_model("people", "Person")
    ModuleCoordinator = apps.get_model("people", "ModuleCoordinator")
    
    # Get all users with COORDINATOR role
    coordinators = Person.objects.filter(role="COORDINATOR")
    
    for coordinator in coordinators:
        # Check if they already have a module coordinator assignment
        existing = ModuleCoordinator.objects.filter(
            person=coordinator,
            module="CLUSTER"
        ).exists()
        
        if not existing:
            # Create a Cluster Coordinator assignment
            # Use COORDINATOR level (not SENIOR_COORDINATOR) to maintain existing behavior
            ModuleCoordinator.objects.create(
                person=coordinator,
                module="CLUSTER",
                level="COORDINATOR",
                resource_id=None,  # Module-wide access
                resource_type=""
            )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Remove Cluster Coordinator assignments.
    Note: This doesn't restore the COORDINATOR role, as we're keeping the role field.
    """
    ModuleCoordinator = apps.get_model("people", "ModuleCoordinator")
    ModuleCoordinator.objects.filter(module="CLUSTER", level="COORDINATOR").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_add_module_coordinator"),
    ]

    operations = [
        migrations.RunPython(
            migrate_coordinators_to_module_assignments,
            reverse_migration
        ),
    ]
