# Generated by Django 4.2.23 on 2025-11-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_clusterweeklyreport"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clusterweeklyreport",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="clusterweeklyreport",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="clusterweeklyreport",
            name="members_attended",
        ),
        migrations.RemoveField(
            model_name="clusterweeklyreport",
            name="submitted_by",
        ),
        migrations.RemoveField(
            model_name="clusterweeklyreport",
            name="visitors_attended",
        ),
        migrations.DeleteModel(
            name="Cluster",
        ),
        migrations.DeleteModel(
            name="ClusterWeeklyReport",
        ),
    ]
