# Generated by Django 4.2.23 on 2025-12-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_migrate_coordinators_to_module_assignments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Short code for the branch (e.g., 'HQ', 'BRANCH1')",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "is_headquarters",
                    models.BooleanField(
                        default=False, help_text="Mark this branch as the headquarters"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Branches",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="journey",
            name="type",
            field=models.CharField(
                choices=[
                    ("LESSON", "Lesson"),
                    ("BAPTISM", "Baptism"),
                    ("SPIRIT", "Spirit"),
                    ("CLUSTER", "Cluster"),
                    ("NOTE", "Note"),
                    ("EVENT_ATTENDANCE", "Event Attendance"),
                    ("MINISTRY", "Ministry"),
                    ("BRANCH_TRANSFER", "Branch Transfer"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Cluster",
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["is_headquarters"], name="people_bran_is_head_208461_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["is_active"], name="people_bran_is_acti_f26a44_idx"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="The church branch this person belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="people.branch",
            ),
        ),
    ]
