# Generated by Django 4.2.23 on 2026-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_modulecoordinator_reporter_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
