# Generated by Django 4.2.23 on 2026-07-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_family_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('SEMIACTIVE', 'Semiactive'), ('INACTIVE', 'Inactive'), ('DORMANT', 'Dormant'), ('FALLAWAY', 'Fall Away'), ('DECEASED', 'Deceased'), ('INVITED', 'Invited'), ('ATTENDED', 'Attended')], max_length=20),
        ),
    ]
