# Generated by Django 4.2.23 on 2026-07-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_person_status_dormant_fallaway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
