# Generated by Django 4.2.23 on 2026-07-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_person_maiden_name_and_visitor_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['user', '-date'], name='people_journey_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['user', 'type'], name='people_journey_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['role'], name='people_person_role_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['status'], name='people_person_status_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['member_id'], name='people_person_member_id_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['branch', 'last_name', 'first_name'], name='people_person_branch_name_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['branch', 'role'], name='people_person_branch_role_idx'),
        ),
    ]
