# Generated by Django 4.2.23 on 2026-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_person_journey_list_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['is_active'], name='people_family_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['branch', 'name'], name='people_family_branch_name_idx'),
        ),
    ]
