# Generated by Django 4.2.23 on 2026-07-17 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_people_automation_setting(apps, schema_editor):
    PeopleAutomationSetting = apps.get_model("people", "PeopleAutomationSetting")
    PeopleAutomationSetting.objects.get_or_create(
        pk=1,
        defaults={"auto_status_updates_enabled": True},
    )


def unseed_people_automation_setting(apps, schema_editor):
    PeopleAutomationSetting = apps.get_model("people", "PeopleAutomationSetting")
    PeopleAutomationSetting.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_person_lessons_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleAutomationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_status_updates_enabled', models.BooleanField(default=True, help_text='When enabled, ACTIVE/SEMIACTIVE/INACTIVE are auto-updated from attendance patterns. Manual pastoral statuses are never overwritten.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_people_automation_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'People Automation Setting',
                'verbose_name_plural': 'People Automation Settings',
            },
        ),
        migrations.RunPython(
            seed_people_automation_setting,
            unseed_people_automation_setting,
        ),
    ]
