# Generated by Django 4.2.23 on 2026-09-12 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0021_people_automation_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonStatusChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SEMIACTIVE", "Semiactive"),
                            ("INACTIVE", "Inactive"),
                            ("DORMANT", "Dormant"),
                            ("FALLAWAY", "Fall Away"),
                            ("DECEASED", "Deceased"),
                            ("ONGOING", "Ongoing"),
                            ("NO_RESPONSE", "No Response"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SEMIACTIVE", "Semiactive"),
                            ("INACTIVE", "Inactive"),
                            ("DORMANT", "Dormant"),
                            ("FALLAWAY", "Fall Away"),
                            ("DECEASED", "Deceased"),
                            ("ONGOING", "Ongoing"),
                            ("NO_RESPONSE", "No Response"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("AUTO_ATTENDANCE", "Auto attendance"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_status_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person Status Change",
                "verbose_name_plural": "Person Status Changes",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="personstatuschange",
            index=models.Index(
                fields=["person", "-created_at"],
                name="people_statuschg_person_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personstatuschange",
            index=models.Index(
                fields=["to_status"],
                name="people_statuschg_to_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personstatuschange",
            index=models.Index(
                fields=["source"],
                name="people_statuschg_source_idx",
            ),
        ),
    ]
