# Generated by Django 4.2.23 on 2026-09-12 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0022_person_status_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCareCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "recommended_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "FOLLOW_UP_MONITOR",
                                "Follow up and monitor progress",
                            ),
                            ("VISITATION", "Visitation and follow up"),
                            ("NO_ACTION", "No action for now"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "recommended_action_other",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "assigned_to_label",
                    models.CharField(blank=True, max_length=150),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In progress"),
                            ("NO_ACTION", "No action"),
                            ("COMPLETED", "Completed"),
                            ("RECOVERED", "Recovered"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_case",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_status_change",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="care_cases",
                        to="people.personstatuschange",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_member_care_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Care Case",
                "verbose_name_plural": "Member Care Cases",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="membercarecase",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_member_care_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="membercarecase",
            index=models.Index(
                fields=["case_status"],
                name="people_carecase_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membercarecase",
            index=models.Index(
                fields=["recommended_action"],
                name="people_carecase_action_idx",
            ),
        ),
    ]
