# Generated by Django 4.2.23 on 2026-06-02 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0010_modulesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier used to group lesson versions together.', max_length=50)),
                ('version_label', models.CharField(default='v1', help_text='Short label that indicates the lesson revision (e.g., v1, v2).', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('outline', models.TextField(blank=True, help_text='Optional structured outline or talking points for the lesson.')),
                ('order', models.PositiveSmallIntegerField(help_text='Display order within the conversion journey.')),
                ('is_latest', models.BooleanField(default=True, help_text='Marks the latest published version for this lesson code.')),
                ('is_active', models.BooleanField(default=True, help_text='Allows disabling a lesson version without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonStudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_signed', models.BooleanField(default=False)),
                ('commitment_signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_enrollments_assigned', to=settings.AUTH_USER_MODEL)),
                ('commitment_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_commitments_verified', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_enrollment', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), on_delete=django.db.models.deletion.PROTECT, related_name='lesson_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_assigned', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_verified', to=settings.AUTH_USER_MODEL)),
                ('journey', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_progress', to='people.journey')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lessons.lesson')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lesson__order', 'person__last_name', 'person__first_name'],
            },
        ),
        migrations.CreateModel(
            name='LessonTeacherTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='lessons.lessonstudentenrollment')),
                ('from_teacher', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('to_teacher', models.ForeignKey(limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), on_delete=django.db.models.deletion.PROTECT, related_name='lesson_transfers_to', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_transfers_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_form', models.FileField(blank=True, null=True, upload_to='lessons/commitment_forms/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_commitment_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonSessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('LESSON', 'Lesson'), ('PRE_LESSON', 'Pre-lesson')], default='LESSON', max_length=20)),
                ('pre_lesson_kind', models.CharField(blank=True, choices=[('INTRODUCTION', 'Introduction'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('session_date', models.DateField()),
                ('session_start', models.DateTimeField()),
                ('score', models.CharField(blank=True, max_length=100)),
                ('next_session_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reports', to='lessons.lesson')),
                ('progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reports', to='lessons.personlessonprogress')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_reports_as_student', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_reports_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-session_date', '-session_start', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LessonJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('LESSON', 'Lesson'), ('BAPTISM', 'Baptism'), ('SPIRIT', 'Spirit'), ('CLUSTER', 'Cluster'), ('NOTE', 'Note'), ('EVENT_ATTENDANCE', 'Event Attendance'), ('SUNDAY_SCHOOL', 'Sunday School'), ('MINISTRY', 'Ministry'), ('BRANCH_TRANSFER', 'Branch Transfer')], default='LESSON', help_text='Journey type to create when the lesson is completed.', max_length=20)),
                ('title_template', models.CharField(blank=True, help_text='Optional override for the journey title (defaults to lesson title).', max_length=100)),
                ('note_template', models.TextField(blank=True, help_text='Optional note body saved on the journey when the lesson is completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey_config', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Journey Configuration',
                'verbose_name_plural': 'Lesson Journey Configurations',
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('code', 'version_label'), name='unique_lesson_code_version'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('code',), name='unique_latest_lesson_per_code'),
        ),
        migrations.AlterUniqueTogether(
            name='personlessonprogress',
            unique_together={('person', 'lesson')},
        ),
    ]
