# Generated by Django 4.2.23 on 2025-11-08 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0002_default_lessons"),
    ]

    operations = [
        migrations.AddField(
            model_name="personlessonprogress",
            name="commitment_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personlessonprogress",
            name="commitment_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personlessonprogress",
            name="commitment_signed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons_commitments_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lessonmilestone",
            name="milestone_type",
            field=models.CharField(
                choices=[
                    ("LESSON", "Lesson"),
                    ("BAPTISM", "Baptism"),
                    ("SPIRIT", "Spirit"),
                    ("CLUSTER", "Cluster"),
                    ("NOTE", "Note"),
                    ("EVENT_ATTENDANCE", "Event Attendance"),
                ],
                default="LESSON",
                help_text="Milestone type to create when the lesson is completed.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LessonSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commitment_form",
                    models.FileField(
                        blank=True, null=True, upload_to="lessons/commitment_forms/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_commitment_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
