# Generated by Django 4.2.23 on 2026-08-12 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0002_default_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstudentenrollment',
            name='historical_teacher_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lessonstudentenrollment',
            name='historical_teacher_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='lessonstudentenrollment',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonteachertransfer',
            name='to_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_transfers_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
