# Generated by Django 4.2.23 on 2026-09-10 12:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0004_to_teacher_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsettings',
            name='ncc_lessons_pdf',
            field=models.FileField(blank=True, null=True, upload_to='lessons/ncc_lessons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='lessonsettings',
            name='ncc_lessons_pdf_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonsettings',
            name='ncc_lessons_pdf_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ncc_lessons_pdfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
