# Generated by Django 4.2.23 on 2026-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_lessonsessionreport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonsessionreport",
            options={"ordering": ("-session_date", "-session_start", "-created_at")},
        ),
        migrations.AlterField(
            model_name="lessonjourney",
            name="journey_type",
            field=models.CharField(
                choices=[
                    ("LESSON", "Lesson"),
                    ("BAPTISM", "Baptism"),
                    ("SPIRIT", "Spirit"),
                    ("CLUSTER", "Cluster"),
                    ("NOTE", "Note"),
                    ("EVENT_ATTENDANCE", "Event Attendance"),
                    ("SUNDAY_SCHOOL", "Sunday School"),
                    ("MINISTRY", "Ministry"),
                    ("BRANCH_TRANSFER", "Branch Transfer"),
                ],
                default="LESSON",
                help_text="Journey type to create when the lesson is completed.",
                max_length=20,
            ),
        ),
    ]
