# Generated by Django 4.2.23 on 2026-09-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0021_people_automation_setting"),
        ("lessons", "0005_ncc_lessons_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonsessionreport",
            name="journey",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pre_lesson_session_report",
                to="people.journey",
            ),
        ),
    ]
