# Generated by Django 4.2.23 on 2026-06-01 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0005_alter_lessonsessionreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_enrollments_assigned', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_enrollment', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), on_delete=django.db.models.deletion.PROTECT, related_name='lesson_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='LessonTeacherTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='lessons.lessonstudentenrollment')),
                ('from_teacher', models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('to_teacher', models.ForeignKey(limit_choices_to=models.Q(('role', 'VISITOR'), _negated=True), on_delete=django.db.models.deletion.PROTECT, related_name='lesson_transfers_to', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_transfers_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
